name: Deploy Blog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies via poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install
        poetry run ./setup.sh

    - name: create static website
      run: |
        poetry run make publish

    # more descriptive validation at https://c3voc.de/schedulexml/validate

    #- name: Validate XML
    #  run: |
    #    wget https://raw.githubusercontent.com/voc/schedule/master/validator/xsd/schedule.xml.xsd
    #    xmlstarlet val -s schedule.xml.xsd schedule-ita.xml

    - name: Commit result
      run: |
        git config --global user.name 'Github Action'
        git config --global user.email 'github-action@users.noreply.github.com'
        git commit -am "Generated new blog release"
        git push
